//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userdetail
    {
        public int UserId { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Gender { get; set; }
        public string phone_no { get; set; }
        public Nullable<System.DateTime> User_DOB { get; set; }
        public string User_Address { get; set; }
        public string User_Staus { get; set; }
    }
}
